# -*- coding: utf-8 -*-
"""removeSquirrels

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VCIqOLXejmLzS99wocZCx-XVXHhhaCF
"""

#takes a list of 5 filenames of jpeg files and a list of masks for the squirrels in each of them,
#and writes a series of 5 files to the present directory, appending to the prefix (coming before .jpg) to their
#filenames “-squirrelsRemoved.jpg”. The squirrels are to removed in these images by inpainting.

from google.colab import drive

#for authorisation
drive.mount('/content/drive')

#Drive files in "/content/drive/My Drive".
!ls "/content/drive/My Drive"

#!pip install --upgrade pip

#!pip install diffusers
#!pip install transformers
#!pip install torch
#!pip install accelerate

folderPath='/content/drive/My Drive/'
filename='file.jpg'
newPath=folderPath+filename
newPath

import cv2
  import numpy as np
  import tensorflow as tf
  import os

#None of these codes work, all of them are jumbled around, but this is me trying a bunch of different methods.

def removeSquirrel(fiveJPEGfilenames, squirrelMasks):

length= len(fiveJPEGfilenames)

  for i in length:
    image=cv2.imread(fiveJPEGfilenames[i])

    preImpaintedImage=image.copy()

    mask1 = np.uint8(squirrelMasks[i])
    inpaintedImage=cv2.inpaint(preImpaintedImage, mask1, 3, cv2.INPAINT_TELEA)

    orgFilename, extension = os.path.splitext(fname)
    newFilename= f"{orgFilename}-squirrelsRemoved{extension}"
    cv2.imwrite(newFilename, inpaintedImage)

import tensorflow as tf
  import cv2
  import numpy as np

def removeSquirrel1(fileList,squirrelMasks):

  filenames_without_ext=[]

  #First I need to read in all of the original images:

  for i, fl in enumerate(fileList):

    inSquirrelIm=cv2.imread(fl)

#    print(inSquirrelIm.shape, inSquirrelIm.dtype)
#    print(squirrelMask[i].shape, squirrelMask[i].dtype)

    name_without_ext= fl.split('.')[0]

#    print(squirrelMasks)

    if mask.shape[-1] != inSquirrelIm.shape[-1]:
      mask= np.expand_dims(mask, axis=-1)

#    _, thresholded_mask = cv2.threshold(squirrelMask[i], 1, 255, cv2.THRESH_BINARY)

    mask_image = squirrelMask[i].convert('L')  # Convert to grayscale
    mask_image = mask_image.point(lambda x: 255 if x > 0 else 0, '1')

    dst = cv2.inpaint(inSquirrelIm, mask_image, 3, cv2.INPAINT_NS)
    cv2.imwrite('/content/drive/My Drive/squirrelsGone/'+name_without_ext+'-squirrelsRemoved.jpg', dst)


#    sqMask=cv2.imread(sqMsk)
#    squirrelMasks = sqMsk.np()
#    squirrelMasks1= np.uint8(*255)

#    print(sqMsk.shape, sqMsk.dtype)

def removeSquirrel2(fileList,squirrelMasks):

  import tensorflow as tf

  filenames_without_ext=[]

  #First I need to read in all of the original images:

  for fl in fileList:
    image_path = '/content/drive/My Drive/squirrel_birdfeeder_random/' + fl

    inSquirrelIm=tf.io.decode_jpeg(tf.io.read_file(image_path),channels=3)

    name_without_ext= fl.split('.')[0]
    filenames_without_ext.append(name_without_ext)

#    print(inSquirrelIm.shape, inSquirrelIm.dtype)

  #Then I need to load the squirrel masks.

  for sqMsk in squirrelMask:
    squirrelMasks = tf.convert_to_tensor(sqMsk)
    print(squirrelMasks.shape, squirrelMasks.dtype)

def removeSquirrel3(fileList, squirrelMasks):

  from PIL import Image
  import matplotlib.pyplot as plt

  for i in range(len(fileList)):
      image_path = '/content/drive/My Drive/squirrel_birdfeeder_random/'+ fileList[i]
      original_image = Image.open(image_path).resize((512, 512))
      masked_image = Image.open(squirrelMasks[i]).resize((512, 512))
      prompt = 'Grass field, high resolution'
      inpainted_image = pipeline(prompt=prompt, image=original_image, mask_image=masked_image).images[0]

      plt.imshow(inpainted_image)