# -*- coding: utf-8 -*-
"""birderModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1suowzW36aQVzlPc5BF9CIAecrHRWJCYe
"""

#This code is to differentiate between 1. Birds (no squirrels/chipmunks) 2. Squirrel/Chipmunk
#3. feeder or tree without squirrels, chipmunks, or birds.
#Mount drive.

from google.colab import drive

#for authorisation
drive.mount('/content/drive')

#Drive files in "/content/drive/My Drive".
!ls "/content/drive/My Drive"

import tensorflow as tf
import numpy as np

filepath=['/content/drive/My Drive/birds-20-eachOf-358.tfrecords']
filepath1=['/content/drive/My Drive/birds-10-eachOf-358.tfrecords']

raw_birdType_training_dataset=tf.data.TFRecordDataset(filepath)
raw_birdType_validation_dataset=tf.data.TFRecordDataset(filepath1)

#Need to create testing set from given sets.
datLen=raw_birdType_validation_dataset.reduce(0,lambda x,y: x+1)

n_train=int(datLen.numpy()*.7)
n_test=int(datLen.numpy()*.3)

feature_description={'image':tf.io.FixedLenFeature([],tf.string),'birdType':tf.io.FixedLenFeature([],tf.int64)}

#Define parse example to load data.

def parse_examples(serialized_examples):
  examples=tf.io.parse_example(serialized_examples,feature_description)
  targets=examples.pop('birdType')
  images=tf.image.resize_with_pad(tf.cast(tf.io.decode_jpeg(examples['image'],channels=3),tf.float32),299,299)
  return images, targets

#Load in dataset.
#But do I want to load it as supervised.
training_dataset_BT=raw_birdType_training_dataset.take(n_train).map(parse_examples,num_parallel_calls=tf.data.AUTOTUNE)
validation_dataset_BT=raw_birdType_validation_dataset.map(parse_examples,num_parallel_calls=tf.data.AUTOTUNE)

testing_dataset_BT=raw_birdType_validation_dataset.skip(n_train).take(n_test).map(parse_examples,num_parallel_calls=tf.data.AUTOTUNE)

#Preprocessing layer.

def preproc(image,label):
  inp=tf.keras.applications.xception.preprocess_input(image)
  return inp,label

#Apply preprocessing layer.

training_dataset_BT1=training_dataset_BT.take(n_train).map(preproc,num_parallel_calls=tf.data.AUTOTUNE).batch(64)
validation_dataset_BT1=validation_dataset_BT.map(preproc,num_parallel_calls=tf.data.AUTOTUNE).batch(64)

testing_dataset_BT1=testing_dataset_BT.skip(n_train).take(n_test).map(preproc,num_parallel_calls=tf.data.AUTOTUNE).batch(64)

#Defining model.
#Remove top layer and look.

base_model=tf.keras.applications.xception.Xception(weights='imagenet',include_top=False)
#base_model.summary()

#Add new top layer.
avg=tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
output=tf.keras.layers.Dense(358,activation="softmax")(avg)
model=tf.keras.models.Model(inputs=base_model.input,outputs=output)
#model.summary()

#Freeze the weights of the lower layers.
#Why when print, the last two are true? SHouldn't it just be the last?

for layer in base_model.layers:
  layer.trainable=True

#for layer in model.layers:
#  print(layer.trainable)

top5err=tf.keras.metrics.SparseTopKCategoricalAccuracy(k=5,name='top5')
top10err=tf.keras.metrics.SparseTopKCategoricalAccuracy(k=10,name='top10')
top20err=tf.keras.metrics.SparseTopKCategoricalAccuracy(k=20,name='top20')

#Fit the new upper layer.

checkpoint_cb=tf.keras.callbacks.ModelCheckpoint('BirdSquirrelMod-topFit.h5',
save_best_only=True)

earlyStop_cb=tf.keras.callbacks.EarlyStopping(patience=10,restore_best_weights=True)

ss=0.8

opt=tf.keras.optimizers.SGD(learning_rate=ss)

model.compile(loss="sparse_categorical_crossentropy",optimizer=opt,metrics=['accuracy',top5err,top10err,top20err])

model.fit(training_dataset_BT1,validation_data=validation_dataset_BT1,epochs=30,callbacks=[checkpoint_cb,earlyStop_cb])

model.save('/content/drive/My Drive/birder2')

#Unfreeze lower layers?