# -*- coding: utf-8 -*-
"""preprocessDefinition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JD2LpE227kzKLz4b8P1Wp8ovPwghYwqa
"""

#Defining the preprocessing layer.

def preproc(image,label):
  inp=tf.keras.applications.xception.preprocess_input(image)
  return inp,label

def preprocessWithAspectRatio(image,label):
resized_image=tf.image.resize_with_pad(image,299,299)
final_image=keras.applications.xception.preprocess_input(resized_image)
return final_image, label