# -*- coding: utf-8 -*-
"""Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XDUI2xmx2jVIq41vY-0c_TxHCYU8yh-
"""

#Need to create preprocessing layer.

def preproc(image,label):
  inp=keras.applications.xception.preprocess_input(image)
  return inp,label

#Do I only use this, because you want heterogenous outputs to be put into
def preprocessWithAspectRatio(image,label):
  resized_image=tf.image.resize_with_pad(image,299,299)
  final_image=keras.applications.xception.preprocess_input(resized_image)
  return final_image, label

trainPipeAug=trainPipeAug.map(preproc,num_parallel_calls=32).batch(64).prefetch(1)

validPipe=validSet.map(preprocessWithAspectRatio,num_parallel_calls=32).batch(64).prefetch(1)

testPipe=testSet.map(preprocessWithAspectRatio,num_parallel_calls=32).batch(64).prefetch(1)