# -*- coding: utf-8 -*-
"""connToTXT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sprksh-crypto/WIP/blob/main/connToTXT2.ipynb
"""

!pip install torch

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive"

import torch
w = torch.load('/content/drive/My Drive/mnist_784_256_256_10_with_50%_Sparsity[1].dict', map_location=torch.device('cpu'))

print(w)

w.keys()

print(w['layers.0.weight'])

print(w['layers.0.weight'].shape)

print(w['layers.0.weight'].shape[1])

print(w['layers.0.weight'].shape[0])

print(w['layers.4.weight'].shape[0])

print(w['layers.4.weight'].shape)

connectivity_dict1 =[]
connectivity_dict1.append("Network Architecture Parameters:"+str(w['layers.0.weight'].shape[1])+ " " + str(w['layers.0.weight'].shape[0])+" "+str(w['layers.4.weight'].shape[0]))

for key in w.keys():
    if key.endswith('.weight'):
        # Extract the numeric part of the key (e.g., 'layers.0', 'layers.1', etc.)
        layer_number = key.split('.')[1]

        connectivity_dict1.append('Conn:' + ' ' + str(layer_number) + ' ' + str((int(layer_number)+1)))

        for i in range (w[key].shape[0]):
          for j in range(w[key].shape[1]):
            weight_value = w[key][i][j]
            if weight_value != 0:
              connectivity_dict1.append([j, i, float(weight_value)])

    if key.endswith('.threshold'):
        connectivity_dict1.append(f'Threshold: {float(w[key]):.2f}')

    if key.endswith('.reset_mechanism_val'):
        connectivity_dict1.append(f'Reset: {float(w[key]):.2f}')

    if key.endswith('.beta'):
        connectivity_dict1.append(f'Beta: {float(w[key]):.2f}')

for entry in connectivity_dict1[:5]:
    print(entry)

with open('mnist_784_256_256_10_s50_dict.txt', 'w') as file:
    file.write(str(connectivity_dict1))
