# -*- coding: utf-8 -*-
"""connToTXT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sprksh-crypto/WIP/blob/main/connToTXT.ipynb
"""

!pip install torch

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive"

import torch
w = torch.load('/content/drive/My Drive/mnist_784_256_256_10_with_10%_Sparsity[1].dict', map_location=torch.device('cpu'))

print(w)

w.keys()

print(w['layers.0.weight'])

connectivity_dict =[]

connectivity_dict.append('Conn: 0 1')

for i in range(w['layers.0.weight'].shape[0]):
    # Loop through the columns
    for j in range(w['layers.0.weight'].shape[1]):
        weight_value = w['layers.0.weight'][i][j]
        if weight_value != 0:
            connectivity_dict.append([i, j, float(weight_value)])

connectivity_dict.append('Threshold:' + str(float(w['layers.1.threshold'])))
connectivity_dict.append('Reset:' + str(float(w['layers.1.reset_mechanism_val'])))
connectivity_dict.append('Beta:' + str(float(w['layers.1.beta'])))

for entry in connectivity_dict[-5:]:
    print(entry)

print(len(connectivity_dict))

connectivity_dict1 =[]

for key in w.keys():
    if key.endswith('.weight'):
        # Extract the numeric part of the key (e.g., 'layers.0', 'layers.1', etc.)
        layer_number = key.split('.')[1]

        connectivity_dict1.append('Conn:' + ' ' + str(layer_number) + ' ' + str((int(layer_number)+1)))

        for i in range (w[key].shape[0]):
          for j in range(w[key].shape[1]):
            weight_value = w[key][i][j]
            if weight_value != 0:
              connectivity_dict1.append([j, i, float(weight_value)])

    if key.endswith('.threshold'):
        connectivity_dict1.append(f'Threshold: {float(w[key]):.2f}')

    if key.endswith('.reset_mechanism_val'):
        connectivity_dict1.append(f'Reset: {float(w[key]):.2f}')

    if key.endswith('.beta'):
        connectivity_dict1.append(f'Beta: {float(w[key]):.2f}')

for entry in connectivity_dict1[:5]:
    print(entry)

for entry in connectivity_dict1[180630:180640]:
    print(entry)

with open('mnist_784_256_256_10_s10_dict.txt', 'w') as file:
    file.write(str(connectivity_dict1))
